USE [PROD_ISS_NAV]
GO

/****** Object:  Table [dbo].[INV_MSTCOMPANY]    Script Date: 03/28/2014 11:19:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INV_MSTCOMPANY](
	[CompanyCode] [nvarchar](5) NOT NULL,
	[CompanyName] [nvarchar](50) NULL,
	[Disabled] [tinyint] NOT NULL,
 CONSTRAINT [PK_INV_MSTCOMPANY] PRIMARY KEY CLUSTERED 
(
	[CompanyCode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[INV_MSTCOMPANY] ADD  CONSTRAINT [DF_INV_MSTCOMPANY_Disabled]  DEFAULT ((0)) FOR [Disabled]
GO


