'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TKSUCNavigation class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class TKSUCNavigation

    '''<summary>
    '''PnlNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlNavigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ImgNavFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgNavFirst As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgNavPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgNavPrevious As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgNavNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgNavNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgNavLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgNavLast As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtNavPageNoGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNavPageNoGo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ImgNavGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgNavGo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblNavInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNavInfo As Global.System.Web.UI.WebControls.Label
End Class
